name: Build Workflow

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*.alpha"

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
          architecture: "x64"

      # Create CUDA-enabled executable
      - name: Install CUDA-enabled llama_cpp
        run: |
          pip install --index-url https://abetlen.github.io/llama-cpp-python/whl/cu121 --extra-index-url https://pypi.org/simple llama-cpp-python==v0.2.90

      - name: Install requirements
        run: |
          pip install -r client_requirements.txt

      - name: Run PyInstaller for NVIDIA
        run: |
          pyinstaller --additional-hooks-dir=.\scripts\hooks --add-data ".\src\FreeScribe.client\whisper-assets:whisper\assets" --add-data ".\src\FreeScribe.client\markdown:markdown" --add-data ".\src\FreeScribe.client\assets:assets" --name freescribe-client-nvidia --icon=.\src\FreeScribe.client\assets\logo.ico --noconsole .\src\FreeScribe.client\client.py

      # Create CPU-only executable
      - name: Uninstall CUDA-enabled llama_cpp (if necessary) and install CPU-only llama_cpp
        run: |
          pip uninstall -y llama-cpp-python
          pip install --index-url https://abetlen.github.io/llama-cpp-python/whl/cpu --extra-index-url https://pypi.org/simple llama-cpp-python==v0.2.90

      - name: Run PyInstaller for CPU-only
        run: |
          pyinstaller --additional-hooks-dir=.\scripts\hooks --add-data ".\src\FreeScribe.client\whisper-assets:whisper\assets" --add-data ".\src\FreeScribe.client\markdown:markdown" --add-data ".\src\FreeScribe.client\assets:assets" --name freescribe-client-cpu --icon=.\src\FreeScribe.client\assets\logo.ico --noconsole .\src\FreeScribe.client\client.py

      - name: Set up NSIS
        uses: joncloud/makensis-action@1c9f4bf2ea0c771147db31a2f3a7f5d8705c0105
        with:
          script-file: .\scripts\install.nsi
          additional-plugin-paths: "./scripts/nsis-plugins"

      - name: Check if alpha release
        id: check_alpha
        run: |
          if ("${{ github.ref }}" -like "*.alpha") {
            echo "is_alpha=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "is_alpha=false" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh

      - name: Rename Installer
        run: |
          mv dist/FreeScribeInstaller.exe dist/FreeScribeInstaller_windows.exe
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FreeScribeInstaller_windows.exe
          path: dist/FreeScribeInstaller_windows.exe

  
  build-macos-intel:
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PortAudio
        run: |
          brew install portaudio

      - name: Install requirements
        run: |
          pip install -r client_requirements.txt

      - name: llama_cpp with Metal
        run: |
          pip uninstall -y llama-cpp-python
          pip install --index-url https://abetlen.github.io/llama-cpp-python/whl/metal --extra-index-url https://pypi.org/simple llama-cpp-python==v0.2.90
      - name: Install ffmpeg
        run: |
          brew install ffmpeg

      - name: Build macOS app
        run: |
          ./build-mac.sh
      
      - name: Build PKG installer
        run: |
          ./build-pkg.sh

      - name: Rename Installer
        run: |
          mv dist/FreeScribeInstaller.pkg dist/FreeScribeInstaller_x86_64.pkg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FreeScribeInstaller_x86_64.pkg
          path: dist/FreeScribeInstaller_x86_64.pkg
  
  build-macos-arm:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PortAudio
        run: |
          brew install portaudio

      - name: Install requirements
        run: |
          pip install -r client_requirements.txt

      - name: llama_cpp with Metal
        run: |
          pip uninstall -y llama-cpp-python
          pip install --index-url https://abetlen.github.io/llama-cpp-python/whl/metal --extra-index-url https://pypi.org/simple llama-cpp-python==v0.2.90
          
      - name: Install ffmpeg
        run: |
          brew install ffmpeg

      - name: Build macOS app
        run: |
          ./build-mac.sh
      
      - name: Build PKG installer
        run: |
          ./build-pkg.sh

      - name: Rename Installer
        run: |
          mv dist/FreeScribeInstaller.pkg dist/FreeScribeInstaller_arm64.pkg
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FreeScribeInstaller_arm64.pkg
          path: dist/FreeScribeInstaller_arm64.pkg

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos-intel, build-macos-arm]
    steps:
      - name: Download Windows Installer
        uses: actions/download-artifact@v4
        with:
          name: FreeScribeInstaller_windows.exe

      - name: Download Intel Installer
        uses: actions/download-artifact@v4
        with:
          name: FreeScribeInstaller_x86_64.pkg

      - name: Download ARM Installer
        uses: actions/download-artifact@v4
        with:
          name: FreeScribeInstaller_arm64.pkg

      - name: Check if alpha release
        id: check_alpha
        run: |
          if ("${{ github.ref }}" -like "*.alpha") {
            echo "is_alpha=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "is_alpha=false" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh

      - name: Upload Installer
        id: upload-installer
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: FreeScribeInstaller_macos.pkg
          tag_name: ${{ github.ref }}
          body: |
            ## What's Changed
            ${{ steps.changelog.outputs.CHANGELOG }}

            For full changelog, see [the commits since last release](${{ github.server_url }}/${{ github.repository }}/compare/${{ steps.changelog.last_tag }}...${{ github.ref }})
          draft: false
          prerelease: ${{ steps.check_alpha.outputs.is_alpha == 'true' }}
          files: |
            FreeScribeInstaller_arm64.pkg
            FreeScribeInstaller_x86_64.pkg
            FreeScribeInstaller_windows.exe
